{
 "title": "Hetman",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Initialized components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "initializedInput" }
   ]
  },
  {
   "title": "Tailer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    { "expr": "initializedTailer" }
   ]
  },
  {
   "title": "Parser",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "initializedParser" }
   ]
  },
  {
   "title": "Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "initializedBuffer" }
   ]
  },
  {
   "title": "Forwarder",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "initializedForwarder" }
   ]
  },
  { "title": "Log metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Ingested logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ingestedLogCount" }
   ]
  },
  {
   "title": "Forwarded logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "forwardedLogCount" }
   ]
  }
 ]
}