apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hetman-agent
  labels:
    app.kubernetes.io/name: hetman-agent
    app.kubernetes.io/component: logging
spec:
  selector:
    matchLabels:
      name: hetman-agent
  template:
    metadata:
      labels:
        name: hetman-agent
    spec:
      containers:
        - command:
            - /usr/local/bin/hetman 
            - --mode=agent
            - --config-file=/etc/hetman/hetman.agent.yaml
            - --log-level=info
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://grafana-agent:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_SERVICE_NAME
              value: hetman
            - name: FORWARDER_HOST
              value: loki
            - name: FORWARDER_PORT
              value: "3100"
          # Local image
          image: hetman
          # Don't pull image from public registry, use locally built image instead
          imagePullPolicy: Never
          name: hetman-agent
          resources: 
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: config
              mountPath: /etc/hetman/hetman.agent.yaml
              readOnly: true
              subPath: hetman.agent.yaml
      volumes:
        - name: tmplog
          hostPath:
            path: /tmp/hetman
            type: DirectoryOrCreate
        - name: config
          configMap:
            defaultMode: 0640
            name: hetman-agent-config-map
        - name: testlog
          configMap:
            name: hetman-agent-testlog
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hetman-agent-config-map
data:
  hetman.agent.yaml: |-
    global:
      registry_directory: /tmp
      disk_buffer_persistence: true
      backpressure_memory_limit: 1000

    targets:
      - id: containerlog
        type: file
        paths:
          - /var/log/containers/*.log
        parser: 
          format: json
        forwarders:
          - url: http://${FORWARDER_HOST:loki}:${FORWARDER_PORT:3100}/loki/api/v1/push
            add_tags:
              label: hetman
              dest: loki
            compress_request: true 
            probe_readiness: false
